#!/bin/sh
set -e

chmod +x /opt/hp34401a/hp34401a
update-desktop-database -q /usr/share/applications || true
gtk-update-icon-cache -q -f /usr/share/icons/hicolor || true

echo "HP 34401A GUI installiert. Starten mit: hp34401a"
